### ISSUE TITLE
Two db table with same name 'patient_file' in 'healthcare'.

### ISSUE THREAD

**Issue by ankitjain28may** [aayusharora/Hospital#3]
I have found two files named healthcare.sql and patient_file.sql with same table name 'patient_file' in the same database 'healthcare' with different parameters which cant be possible...???

**Comment by aayusharora** [comment]
@aakarshgoel96

**Comment by aakarshgoel96** [comment]
@ankitjain28may ,it was unnecessary file ,deleted now .

**Comment by aakarshgoel96** [comment]
@ankitjain28may ,Closing this.

**Comment by ankitjain28may** [comment]
okkk..!!
